name:                radlang
version:             2.0.1
github:              "radrow/radlang"
license:             BSD2
author:              "Radosław Rowicki"
maintainer:          "rr386088@students.mimuw.edu.pl"
copyright:           "2018 Radosław Rowicki"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/radrow/radlang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 6.5
- containers >= 0.6.0.1
- mtl
- transformers
- ansi-terminal >= 0.8.1
- parser-combinators
- hashtables
- raw-strings-qq
- template-haskell
- syb
- lens
- text

ghc-options:
  - -Wall
  - -Wextra
  - -O2

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - GADTs
    - OverloadedStrings

executables:
  rdl:
    main:                Main.hs
    source-dirs:         rdl
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - radlang
